<?php

/**
 * @file
 * Provides basic integration with the GOV.UK Pay system.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_theme().
 */
function govuk_pay_webform_theme($existing, $type, $theme, $path) {
  return [
    'govuk_pay_webform__govuk_confirmation_page' => [
      'variables' => [
        'payment_id' => NULL,
        'payment_amount' => NULL,
        'payment_status' => NULL,
        'payment_message' => NULL,
        'payment_for' => NULL,
        'payment_reference' => NULL,
        'confirmation_message' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_base_field_info_alter().
 *
 * Adds webform-related entity reference fields to govukpayment entities.
 */
function govuk_pay_webform_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'govukpayment') {
    // Add webform_id as an entity reference to webform entities.
    $fields['webform_id'] = BaseFieldDefinition::create('entity_reference')
      ->setName('webform_id')
      ->setLabel(t('Webform'))
      ->setDescription(t('The Webform entity referenced by this GovUKPayment.'))
      ->setSetting('target_type', 'webform')
      ->setSetting('handler', 'default')
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'entity_reference_label',
        'weight' => -7,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => -7,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'autocomplete_type' => 'tags',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE)
      ->setRevisionable(TRUE);

    // Add submission_id as an entity reference to webform_submission entities.
    $fields['submission_id'] = BaseFieldDefinition::create('entity_reference')
      ->setName('submission_id')
      ->setLabel(t('Submission ID'))
      ->setDescription(t('The Webform Submission entity referenced by this GovUKPayment.'))
      ->setSetting('target_type', 'webform_submission')
      ->setSetting('handler', 'default')
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'entity_reference_label',
        'weight' => -6,
      ])
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => -6,
        'settings' => [
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'autocomplete_type' => 'tags',
          'placeholder' => '',
        ],
      ])
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayConfigurable('form', TRUE)
      ->setRevisionable(TRUE);
  }
}
