<?php

/**
 * @file
 * Provides basic integration with the GOV.UK Pay system.
 */

/**
 * Implements hook_theme().
 */
function govuk_pay_webform_theme($existing, $type, $theme, $path) {
  return [
    'govuk_pay_webform__govuk_confirmation_page' => [
      'variables' => [
        'payment_id' => NULL,
        'payment_amount' => NULL,
        'payment_status' => NULL,
        'payment_message' => NULL,
        'payment_for' => NULL,
        'payment_reference' => NULL,
        'confirmation_message' => NULL,
      ],
    ],
  ];
}
