# Schema for the views plugins of the GOV.UK Pay module.

# Define the custom field plugin for payment amount
views.field.govuk_pay_payment_amount:
  type: views.field.numeric
  label: 'GOV.UK Payment amount field'
  mapping:
    format_plural:
      type: integer
      label: 'Format plural'
    format_plural_string:
      type: string
      label: 'Format plural string'
